public class Exception5 {
   public static void main(String[] args){
      try{
         System.out.println("hello from try block");
      }
      catch(Exception e){

      }
   }
}
